### ISSUE TITLE
Can't install oceansoundscape with python 3.9.13

### ISSUE THREAD

**Issue by cparcerisas** [mbari-org/oceansoundscape#2]
Hi Danelle,

After running:
pip install oceansoundscape

I get: 
ERROR: Ignored the following versions that require a different python version: 2.0.0 Requires-Python >=3.8,<=3.9
ERROR: Could not find a version that satisfies the requirement oceansoundscape (from versions: none)
ERROR: No matching distribution found for oceansoundscape

My python version is 3.9.13

Does it only work with lower versions of 3.9? 
Thanks, 

Clea

**Comment by danellecline** [comment]
Hello @cparcerisas,  It should work for 3.9.13, but I'll need to test that first.  I downloaded Python 3.19.16, the last release before 3.10, and it should be compatible with 3.9.13. These minor releases were mostly security related. I will give it a try tomorrow and report back.  In the meantime, you can also try to adjust the line in pyproject.toml

python = ">=3.8,< 3.10"

to 

python = ">=3.8,<=3.9.16"

or 

python = ">=3.8,<=3.9.13"

Then do a pip install directly from the code to see if that works for you with something like (untested, but I think this is correct)

```
git clone https://github.com/mbari-org/oceansoundscape
cd oceansoundscape
pip install .
```

**Comment by cparcerisas** [comment]
That worked, thanks! 

I changed it to python = ">=3.8,<=3.9.16"
